// <auto-generated />
using CapaDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapaDatos.Migrations
{
    [DbContext(typeof(BDEscuela))]
    [Migration("20260317004616_AgregarCursos")]
    partial class AgregarCursos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapaModelos.Curso", b =>
                {
                    b.Property<int>("CodCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCurso"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesorCodProfesor")
                        .HasColumnType("int");

                    b.HasKey("CodCurso");

                    b.HasIndex("ProfesorCodProfesor");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("CapaModelos.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<int>("CreditosAprobados")
                        .HasColumnType("int");

                    b.Property<int?>("CursoCodCurso")
                        .HasColumnType("int");

                    b.Property<int>("CursosReprobados")
                        .HasColumnType("int");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstudiante");

                    b.HasIndex("CursoCodCurso");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("CapaModelos.Profesor", b =>
                {
                    b.Property<int>("CodProfesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodProfesor"));

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodProfesor");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("CapaModelos.Curso", b =>
                {
                    b.HasOne("CapaModelos.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorCodProfesor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("CapaModelos.Estudiante", b =>
                {
                    b.HasOne("CapaModelos.Curso", null)
                        .WithMany("Estudiantes")
                        .HasForeignKey("CursoCodCurso");
                });

            modelBuilder.Entity("CapaModelos.Curso", b =>
                {
                    b.Navigation("Estudiantes");
                });
#pragma warning restore 612, 618
        }
    }
}
